// <auto-generated />
using System;
using Ejyle.DevAccelerate.Comments.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejyle.DevAccelerate.Files.EF.Migrations
{
    [DbContext(typeof(DaFilesDbContext))]
    partial class DaFilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FileCollectionId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("FileStorageLocationId")
                        .HasColumnType("int");

                    b.Property<string>("GuidFileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ObjectInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileCollectionId");

                    b.HasIndex("GuidFileName")
                        .IsUnique();

                    b.ToTable("Files", "Files");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FileStorageLocationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUserDefined")
                        .HasColumnType("bit");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ObjectInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("FileCollections", "Files");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileStorages", "Files");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileStorageAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileStorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileStorageId");

                    b.ToTable("FileStorageAttributes", "Files");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileStorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FileStorageId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FileStorageId");

                    b.ToTable("FileStorageLocations", "Files");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFile", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.Files.DaFileCollection", "FileCollection")
                        .WithMany("Files")
                        .HasForeignKey("FileCollectionId");

                    b.Navigation("FileCollection");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileCollection", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.Files.DaFileCollection", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileStorageAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.Files.DaFileStorage", "FileStorage")
                        .WithMany("Attributes")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileStorageLocation", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.Files.DaFileStorage", "FileStorage")
                        .WithMany("Locations")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileCollection", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Files.DaFileStorage", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
