// <auto-generated />
using System;
using Ejyle.DevAccelerate.Comments.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejyle.DevAccelerate.Comments.EF.Migrations
{
    [DbContext(typeof(DaCommentsDbContext))]
    [Migration("20221112215550_DaCommentsDbMigration_v7_0_0")]
    partial class DaCommentsDbMigrationv700
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejyle.DevAccelerate.Comments.DaComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentThreadId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentThreadId");

                    b.HasIndex("ParentId");

                    b.ToTable("Comments", "Comments");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Comments.DaCommentThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObjectInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CommentThreads", "Comments");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Comments.DaComment", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.Comments.DaCommentThread", "CommentThread")
                        .WithMany("Comments")
                        .HasForeignKey("CommentThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejyle.DevAccelerate.Comments.DaComment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("CommentThread");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Comments.DaComment", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.Comments.DaCommentThread", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
