// <auto-generated />
using System;
using Ejyle.DevAccelerate.EnterpriseSecurity.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejyle.DevAccelerate.EnterpriseSecurity.EF.Migrations
{
    [DbContext(typeof(DaEnterpriseSecurityDbContext))]
    [Migration("20221112222251_DaEnterpriseSecurityDbMigration_v7_0_0")]
    partial class DaEnterpriseSecurityDbMigrationv700
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Apps", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaAppAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AppAttributes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaAppFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AppFeatures", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Features", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeatureAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureActions", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectHistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNoteHtml")
                        .HasColumnType("bit");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjectInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectInstanceId");

                    b.ToTable("ObjectHistoryItems", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SourceObjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.ToTable("ObjectInstances", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ObjectTypes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaBillingCycleOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BillingInterval")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("BillingCycleOptions", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowTrial")
                        .HasColumnType("bit");

                    b.Property<int>("BillingType")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultBillingCycleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAutoRenewUntilCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PublishedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SetupFee")
                        .HasColumnType("float");

                    b.Property<bool>("StartOnlyWithTrial")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TrialDays")
                        .HasColumnType("int");

                    b.Property<int?>("UserAgreementVersionId")
                        .HasColumnType("int");

                    b.Property<int?>("ValidityInMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("SubscriptionPlans", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("SubscriptionPlanApps", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("SubscriptionPlanAttributes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<double?>("MaximumQuantity")
                        .HasColumnType("float");

                    b.Property<int>("SubscriptionPlanFeatureType")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("SubscriptionPlanFeatures", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanFeatureAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionPlanFeatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanFeatureId");

                    b.ToTable("SubscriptionPlanFeatureAttributes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("BillingCycles", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycleAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BillingCycleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingCycleId");

                    b.ToTable("BillingCycleAttributes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycleFeatureUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCycleId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("SubscriptionFeatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingCycleId");

                    b.HasIndex("SubscriptionFeatureId");

                    b.ToTable("BillingCycleFeatureUsage", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BillingAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("BillingInterval")
                        .HasColumnType("int");

                    b.Property<int>("BillingType")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoRenewUntilCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentlyInTrial")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int?>("LastPaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("LastTransactionId")
                        .HasColumnType("int");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("NextBillingDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrialPeriodEndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrialPeriodStartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TrialStartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserAgreementVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("Subscriptions", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionApps", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionAppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionAppId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionAppId");

                    b.ToTable("SubscriptionAppRoles", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionAppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriptionAppId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionAppId");

                    b.ToTable("SubscriptionAppUsers", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionAttributes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<double?>("MaximumQuantity")
                        .HasColumnType("float");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionPlanFeatureType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionFeatures", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionFeatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionFeatureId");

                    b.ToTable("SubscriptionFeatureAttributes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionFeatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionFeatureId");

                    b.ToTable("SubscriptionFeatureRole", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureRoleAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Allowed")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriptionFeatureRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionFeatureRoleId");

                    b.ToTable("SubscriptionFeatureRoleActions", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriptionFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionFeatureId");

                    b.ToTable("SubscriptionFeatureUsers", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureUserAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Allowed")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriptionFeatureUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionFeatureUserId");

                    b.ToTable("SubscriptionFeatureUserActions", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("DateFormatId")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDomainOwnershipVerified")
                        .HasColumnType("bit");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SystemLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("TenantType")
                        .HasColumnType("int");

                    b.Property<int?>("TimeZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasFilter("[Domain] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenantAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantAttributes", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenantUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUsers", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("UserAgreements", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreementVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublishedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAgreementId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAgreementId");

                    b.ToTable("UserAgreementVersions", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreementVersionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionOwner")
                        .HasColumnType("int");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserAgreementVersionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAgreementVersionId");

                    b.ToTable("UserAgreementVersionActions", "EnterpriseSecurity");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaAppAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", "App")
                        .WithMany("Attributes")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaAppFeature", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", "App")
                        .WithMany("AppFeatures")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeature", "Feature")
                        .WithMany("AppFeatures")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeature", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", "App")
                        .WithMany("Features")
                        .HasForeignKey("AppId");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeatureAction", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeature", "Feature")
                        .WithMany("FeatureActions")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectHistoryItem", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectInstance", "ObjectInstance")
                        .WithMany("ObjectHistoryItems")
                        .HasForeignKey("ObjectInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectInstance");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectInstance", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectType", "ObjectType")
                        .WithMany("ObjectInstances")
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectType");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaBillingCycleOption", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlan", "SubscriptionPlan")
                        .WithMany("BillingCycleOptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanApp", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", "App")
                        .WithMany("SubscriptionPlanApps")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionPlanApps")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Attributes")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanFeature", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeature", "Feature")
                        .WithMany("SubscriptionPlanFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionPlanFeatures")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanFeatureAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanFeature", "SubscriptionPlanFeature")
                        .WithMany("SubscriptionPlanFeatureAttributes")
                        .HasForeignKey("SubscriptionPlanFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlanFeature");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycle", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscription", "Subscription")
                        .WithMany("BillingCycles")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycleAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycle", "BillingCycle")
                        .WithMany("Attributes")
                        .HasForeignKey("BillingCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingCycle");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycleFeatureUsage", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycle", "BillingCycle")
                        .WithMany("FeatureUsage")
                        .HasForeignKey("BillingCycleId")
                        .IsRequired();

                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeature", "SubscriptionFeature")
                        .WithMany("FeatureUsage")
                        .HasForeignKey("SubscriptionFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingCycle");

                    b.Navigation("SubscriptionFeature");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscription", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionApp", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", "App")
                        .WithMany("SubscriptionApps")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscription", "Subscription")
                        .WithMany("SubscriptionApps")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionAppRole", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionApp", "SubscriptionApp")
                        .WithMany("SubscriptionAppRoles")
                        .HasForeignKey("SubscriptionAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionApp");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionAppUser", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionApp", "SubscriptionApp")
                        .WithMany("SubscriptionAppUsers")
                        .HasForeignKey("SubscriptionAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionApp");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscription", "Subscription")
                        .WithMany("Attributes")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeature", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeature", "Feature")
                        .WithMany("SubscriptionFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscription", "Subscription")
                        .WithMany("SubscriptionFeatures")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeature", "SubscriptionFeature")
                        .WithMany("SubscriptionFeatureAttributes")
                        .HasForeignKey("SubscriptionFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionFeature");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureRole", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeature", "SubscriptionFeature")
                        .WithMany("SubscriptionFeatureRoles")
                        .HasForeignKey("SubscriptionFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionFeature");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureRoleAction", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureRole", "SubscriptionFeatureRole")
                        .WithMany("SubscriptionFeatureRoleActions")
                        .HasForeignKey("SubscriptionFeatureRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionFeatureRole");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureUser", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeature", "SubscriptionFeature")
                        .WithMany("SubscriptionFeatureUsers")
                        .HasForeignKey("SubscriptionFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionFeature");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureUserAction", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureUser", "SubscriptionFeatureUser")
                        .WithMany("SubscriptionFeatureUserActions")
                        .HasForeignKey("SubscriptionFeatureUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionFeatureUser");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenantAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenant", "Tenant")
                        .WithMany("Attributes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenantUser", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreement", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", "App")
                        .WithMany("UserAgreements")
                        .HasForeignKey("AppId");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreementVersion", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreement", "UserAgreement")
                        .WithMany("UserAgreementVersions")
                        .HasForeignKey("UserAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAgreement");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreementVersionAction", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreementVersion", "UserAgreementVersion")
                        .WithMany("Actions")
                        .HasForeignKey("UserAgreementVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAgreementVersion");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaApp", b =>
                {
                    b.Navigation("AppFeatures");

                    b.Navigation("Attributes");

                    b.Navigation("Features");

                    b.Navigation("SubscriptionApps");

                    b.Navigation("SubscriptionPlanApps");

                    b.Navigation("UserAgreements");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Apps.DaFeature", b =>
                {
                    b.Navigation("AppFeatures");

                    b.Navigation("FeatureActions");

                    b.Navigation("SubscriptionFeatures");

                    b.Navigation("SubscriptionPlanFeatures");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectInstance", b =>
                {
                    b.Navigation("ObjectHistoryItems");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Objects.DaObjectType", b =>
                {
                    b.Navigation("ObjectInstances");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlan", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("BillingCycleOptions");

                    b.Navigation("SubscriptionPlanApps");

                    b.Navigation("SubscriptionPlanFeatures");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.SubscriptionPlans.DaSubscriptionPlanFeature", b =>
                {
                    b.Navigation("SubscriptionPlanFeatureAttributes");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaBillingCycle", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("FeatureUsage");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscription", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("BillingCycles");

                    b.Navigation("SubscriptionApps");

                    b.Navigation("SubscriptionFeatures");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionApp", b =>
                {
                    b.Navigation("SubscriptionAppRoles");

                    b.Navigation("SubscriptionAppUsers");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeature", b =>
                {
                    b.Navigation("FeatureUsage");

                    b.Navigation("SubscriptionFeatureAttributes");

                    b.Navigation("SubscriptionFeatureRoles");

                    b.Navigation("SubscriptionFeatureUsers");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureRole", b =>
                {
                    b.Navigation("SubscriptionFeatureRoleActions");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Subscriptions.DaSubscriptionFeatureUser", b =>
                {
                    b.Navigation("SubscriptionFeatureUserActions");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.Tenants.DaTenant", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("TenantUsers");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreement", b =>
                {
                    b.Navigation("UserAgreementVersions");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.EnterpriseSecurity.UserAgreements.DaUserAgreementVersion", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
