// <auto-generated />
using System;
using Ejyle.DevAccelerate.SystemTasks.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejyle.DevAccelerate.SystemTasks.EF.Migrations
{
    [DbContext(typeof(DaSystemTasksDbContext))]
    partial class DaSystemTasksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejyle.DevAccelerate.SystemTasks.DaSystemTaskDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDataType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SystemTaskData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemTaskDataType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SystemTaskType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("SystemTaskDefinitions", "SystemTasks");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.SystemTasks.DaSystemTaskDefinitionAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SystemTaskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SystemTaskId");

                    b.ToTable("SystemTaskDefinitionAttributes", "SystemTasks");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.SystemTasks.DaSystemTaskDefinitionAttribute", b =>
                {
                    b.HasOne("Ejyle.DevAccelerate.SystemTasks.DaSystemTaskDefinition", "SystemTask")
                        .WithMany("Attributes")
                        .HasForeignKey("SystemTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemTask");
                });

            modelBuilder.Entity("Ejyle.DevAccelerate.SystemTasks.DaSystemTaskDefinition", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
